### PR TITLE
Update Prana to Karyon 2.7.1

### PR DESCRIPTION
**Pull request by jaume-pinyol**
Hi,

I've updated Prana to karyon 2.7.1.
It solves issues like #1 and #14

### CODE REVIEW

**Comment by nmdguerreiro** [comment]
@jaume-pinyol I've only been able to compile this branch by adding the following dependencies:

```gradle
    compile 'com.netflix.hystrix:hystrix-core:1.4.14'
    compile 'com.netflix.ribbon:ribbon:2.1.0'
    compile 'com.netflix.ribbon:ribbon-eureka:2.1.0'
```

**Comment by jaume-pinyol** [comment]
Thanks @nmdguerreiro !

**Comment by aspyker** [comment]
@jaume-pinyol @nmdguerreiro Thank you for the contributions.  More will be coming, but please see http://ispyker.blogspot.com/2015/10/towards-being-better-about-open-source.html for a bit of context on the status of this project.

**Comment by jaume-pinyol** [comment]
@aspyker thanks for the info!

**Pull request closed without merging**
